version: "2"
run:
  timeout: 10m

linters:
  default: none
  enable:
    - copyloopvar
    - dogsled
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - misspell
    - musttag
    - nonamedreturns
    - prealloc
    - revive
    - sloglint
    - staticcheck
    - unconvert
    - unparam
    - whitespace
    - unused
    - usestdlibvars
  settings:
    errcheck:
      exclude-functions:
        - fmt:.*[rR]ead|[wW]rite|[cC]lose
        - io:Copy
    nonamedreturns:
      report-error-in-defer: false
    sloglint:
      no-mixed-args: true
      kv-only: false
      attr-only: false
      no-global: ""
      context: ""
      static-msg: false
      no-raw-keys: false
      key-naming-case: "snake"
      forbidden-keys:
        - level
        - msg
        - logger
        - source
        - stacktrace
        - time
      args-on-sep-lines: false
    staticcheck:
      checks:
        - all
        - '-ST1003' # waiting for package name will be fixed (underscores)
        - '-QF1008' # not need to fix; we understand how to call nested structs
    revive:
      rules:
        - name: var-naming # waiting for package name will be fixed (incorrect naming)
          severity: warning
          disabled: false
          exclude: [""]
          arguments:
            - [] # AllowList
            - [] # DenyList
            - - skip-initialism-name-checks: false
                upper-case-const: false
                skip-package-name-checks: true
                skip-package-name-collision-with-go-std: false
                extra-bad-package-names: []
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: ST1005.*
      - path: (.+)\.go$
        text: should not use dot imports
      - path: (.+)\.go$
        text: don't use an underscore in package name
      - path: (.+)\.go$
        text: 'exported: .*'
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/name212/netpacket)
        - localmodule
    goimports:
      local-prefixes:
        - github.com/name212/netpacket
